language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
install:
  - "cpanm -n Mojo::UserAgent Test::MockObject Test::Fatal Test::Pod"
  - "cpanm -n --installdeps ."
sudo: false
